### ISSUE TITLE
Support font-feature-setting: 'kern'

### ISSUE THREAD

**Issue by mapgrid** [benface/tailwindcss-typography#10]
Since we have `font-variant-*` for most the the features that `font-feature-setting` covers, we could add one rule for `kern` without worrying about overwriting with other features:

```css
.kern {
    font-feature-settings: 'kern';
    font-kerning: normal;
}
```

Happy to submit a PR.
