### ISSUE TITLE
Support text-rendering properties

### ISSUE THREAD

**Issue by mapgrid** [benface/tailwindcss-typography#11]
Although it's an [SVG property](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering), it's widely used for typography. We could add:

```css
.text-optimize-legibility {
    text-rendering: optimizeLegibility;
}

.text-optimize-speed {
    text-rendering: optimizeSpeed;
}

.text-geometric-precision {
    text-rendering: geometricPrecision;
}
```

Happy to submit a PR.
